### ISSUE TITLE
following default instructions results in a build failure

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine_boot#22]
To get here I ran:

```bash
pip install intermine_boot
intermine_boot start local
```

Maybe I did something wrong - let me know. Here's a huge snippet of the error

```bash
intermine_builder    | Fri May 15 11:27:19 UTC 2020
intermine_builder    |
intermine_builder    | starting command: /home/intermine/intermine/biotestmine/gradlew --stacktrace --no-daemon postprocess -Pprocess=summarise-objectstore
intermine_builder    |
intermine_builder    | Fri May 15 11:28:09 UTC 2020
intermine_builder    |
intermine_builder    | finished
intermine_builder    |
intermine_builder    |
intermine_builder    | Fri May 15 11:28:09 UTC 2020
intermine_builder    |
intermine_builder    | starting command: /home/intermine/intermine/biotestmine/gradlew --stacktrace --no-daemon postprocess -Pprocess=create-autocomplete-index
intermine_builder    |
intermine_builder    | Fri May 15 11:29:25 UTC 2020
intermine_builder    |
intermine_builder    | finished
intermine_builder    |
intermine_builder    |
intermine_builder    | Fri May 15 11:29:25 UTC 2020
intermine_builder    |
intermine_builder    | starting command: /home/intermine/intermine/biotestmine/gradlew --stacktrace --no-daemon postprocess -Pprocess=create-search-index
intermine_builder    |
intermine_builder    |
intermine_builder    | FAILURE: Build failed with an exception.
intermine_builder    |
intermine_builder    | * Where:
intermine_builder    | Build file '/home/intermine/intermine/biotestmine/webapp/build.gradle' line: 2
intermine_builder    |
intermine_builder    | * What went wrong:
intermine_builder    | A problem occurred evaluating project ':webapp'.
intermine_builder    | > Could not get resource 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'.
intermine_builder    |    > Could not HEAD 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'. Received status code 503 from server: Backend unavailable, connection timeout
intermine_builder    |
intermine_builder    | * Try:
intermine_builder    | Run with --info or --debug option to get more log output. Run with --scan to get full insights.
intermine_builder    |
intermine_builder    | * Exception is:
intermine_builder    | org.gradle.api.GradleScriptException: A problem occurred evaluating project ':webapp'.
intermine_builder    | 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
intermine_builder    | 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:204)
intermine_builder    | 	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
intermine_builder    | 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:209)
intermine_builder    | 	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
intermine_builder    | 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
intermine_builder    | 	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:58)
intermine_builder    | 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
intermine_builder    | 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
intermine_builder    | 	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
intermine_builder    | 	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:105)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
intermine_builder    | 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
intermine_builder    | 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
intermine_builder    | 	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:682)
intermine_builder    | 	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:138)
intermine_builder    | 	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
intermine_builder    | 	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
intermine_builder    | 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
intermine_builder    | 	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:266)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
intermine_builder    | 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
intermine_builder    | 	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:179)
intermine_builder    | 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:138)
intermine_builder    | 	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:121)
intermine_builder    | 	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
intermine_builder    | 	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
intermine_builder    | 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
intermine_builder    | 	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
intermine_builder    | 	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
intermine_builder    | 	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
intermine_builder    | 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
intermine_builder    | 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
intermine_builder    | 	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
intermine_builder    | 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:47)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
intermine_builder    | 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
intermine_builder    | 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:43)
intermine_builder    | 	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
intermine_builder    | 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
intermine_builder    | 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
intermine_builder    | 	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:74)
intermine_builder    | 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
intermine_builder    | 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
intermine_builder    | 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
intermine_builder    | 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
intermine_builder    | 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
intermine_builder    | 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
intermine_builder    | 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
intermine_builder    | 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
intermine_builder    | 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
intermine_builder    | 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
intermine_builder    | 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
intermine_builder    | 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
intermine_builder    | 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
intermine_builder    | 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
intermine_builder    | 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
intermine_builder    | 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
intermine_builder    | 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
intermine_builder    | 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
intermine_builder    | 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:52)
intermine_builder    | 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:207)
intermine_builder    | 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:402)
intermine_builder    | 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:375)
intermine_builder    | 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:37)
intermine_builder    | 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:23)
intermine_builder    | 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:368)
intermine_builder    | 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:298)
intermine_builder    | 	at org.gradle.launcher.Main.doAction(Main.java:36)
intermine_builder    | 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
intermine_builder    | 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
intermine_builder    | 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
intermine_builder    | 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
intermine_builder    | 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
intermine_builder    | 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
intermine_builder    | 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
intermine_builder    | Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'.
intermine_builder    | 	at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
intermine_builder    | 	at org.gradle.internal.resource.ResourceExceptions.getFailed(ResourceExceptions.java:57)
intermine_builder    | 	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceAccessor.resolve(DefaultExternalResourceAccessor.java:67)
intermine_builder    | 	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceAccessor.resolveUri(DefaultExternalResourceAccessor.java:47)
intermine_builder    | 	at org.gradle.internal.resource.transfer.DefaultUriTextResourceLoader.loadUri(DefaultUriTextResourceLoader.java:43)
intermine_builder    | 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:103)
intermine_builder    | 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:38)
intermine_builder    | 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:68)
intermine_builder    | 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
intermine_builder    | 	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
intermine_builder    | 	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
intermine_builder    | 	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
intermine_builder    | 	at build_da72qw3j0wz3a0g7crxnokdmj.run(/home/intermine/intermine/biotestmine/webapp/build.gradle:2)
intermine_builder    | 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
intermine_builder    | 	... 88 more
intermine_builder    | Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not HEAD 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'. Received status code 503 from server: Backend unavailable, connection timeout
intermine_builder    | 	at org.gradle.internal.resource.transport.http.HttpClientHelper.processResponse(HttpClientHelper.java:158)
intermine_builder    | 	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHead(HttpClientHelper.java:76)
intermine_builder    | 	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.getMetaData(HttpResourceAccessor.java:65)
intermine_builder    | 	at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.getMetaData(DefaultExternalResourceConnector.java:63)
intermine_builder    | 	at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.getMetaData(AccessorBackedExternalResource.java:201)
intermine_builder    | 	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$1.call(BuildOperationFiringExternalResourceDecorator.java:61)
intermine_builder    | 	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$1.call(BuildOperationFiringExternalResourceDecorator.java:58)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:314)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:304)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
intermine_builder    | 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:100)
intermine_builder    | 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
intermine_builder    | 	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.getMetaData(BuildOperationFiringExternalResourceDecorator.java:58)
intermine_builder    | 	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create(DefaultCacheAwareExternalResourceAccessor.java:101)
intermine_builder    | 	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create(DefaultCacheAwareExternalResourceAccessor.java:81)
intermine_builder    | 	at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
intermine_builder    | 	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:81)
intermine_builder    | 	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceAccessor.resolve(DefaultExternalResourceAccessor.java:60)
intermine_builder    | 	... 99 more
intermine_builder    |
intermine_builder    |
intermine_builder    | * Get more help at https://help.gradle.org
intermine_builder    |
intermine_builder    | BUILD FAILED in 5s
intermine_builder    | Fri May 15 11:29:31 UTC 2020
intermine_builder    |
intermine_builder    | finished
intermine_builder    |
intermine_builder    |
intermine_builder    | ERROR: 256
intermine_builder    | failed with exit code 0: /home/intermine/intermine/biotestmine/gradlew --stacktrace --no-daemon postprocess -Pprocess=create-search-index
intermine_builder    |
intermine_builder    | check log: pbuild.log
intermine_builder exited with code 1
Build completed. Visit http://localhost:9999/biotestmine to access your mine.
```

**Comment by heralden** [comment]
This looks like a connection timeout error. Seems to not be that uncommon, so I can only suggest retrying until it succeeds.

There are probably ways we can improve this. One would be to catch that intermine_builder exited with code 1 and showing a helpful message. Currently, this can only be done by matching the stdout of running docker-compose, but there should exist a better approach once we've switched to docker-py.

The other thing would be to make the script that intermine_builder runs more robust, with retryability.

**Comment by 22PoojaGaur** [comment]
@uosl can we close this issue?

**Comment by heralden** [comment]
@22PoojaGaur I think we should let this stay, as a reminder to handle request timeouts in the intermine_builder script and automatically retry a few times.

**Comment by 22PoojaGaur** [comment]
ok

**Comment by heralden** [comment]
This actually needs to be fixed in a different repo, so I created an issue there: https://github.com/intermine/docker-intermine-gradle/issues/13
