### ISSUE TITLE
--build-images flag doesn't seem to work

### ISSUE THREAD

**Issue by heralden** [intermine/intermine_boot#33]
`intermine_boot start local --build-images` returns the following traceback:

```
Traceback (most recent call last):
  File "/home/regen/prog/work/intermine_boot/venv/bin/intermine_boot", line 11, in <module>
    load_entry_point('intermine-boot', 'console_scripts', 'intermine_boot')()
  File "/home/regen/prog/work/intermine_boot/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/regen/prog/work/intermine_boot/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/regen/prog/work/intermine_boot/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/regen/prog/work/intermine_boot/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/regen/prog/work/intermine_boot/intermine_boot/__init__.py", line 38, in cli
    commands.invoke(options['mode'], options, env)
  File "/home/regen/prog/work/intermine_boot/intermine_boot/commands.py", line 65, in invoke
    return func(options, env)
  File "/home/regen/prog/work/intermine_boot/intermine_boot/commands.py", line 34, in start
    intermine_docker.up(options, env)
  File "/home/regen/prog/work/intermine_boot/intermine_boot/intermine_docker.py", line 94, in up
    tomcat_image = client.images.build(
  File "/home/regen/prog/work/intermine_boot/venv/lib/python3.8/site-packages/docker/models/images.py", line 279, in buil
    resp = self.client.api.build(**kwargs)
  File "/home/regen/prog/work/intermine_boot/venv/lib/python3.8/site-packages/docker/api/build.py", line 148, in build
    raise TypeError("You must specify a directory to build in path")
TypeError: You must specify a directory to build in path
```

**Comment by 22PoojaGaur** [comment]
@uosl 
Strange, I have tested with `--build-images` and it works.

Was `git submodule update --init` run on the branch you were checking this?

**Comment by heralden** [comment]
Sorry for the late response!

You're right, I had forgotten to init the submodules. I tested now after running `git submodule update --init` and it works!
